### ISSUE TITLE
Someone should review backend.configuration()

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-jku-provider#22]
```
jku_backend.configuration()
```

gives 

```
BackendConfiguration(backend_name='local_statevector_simulator_jku', backend_version='1.1.0', basis_gates=['u0', 'u1', 'u2', 'u3', 'cx', 'x', 'y', 'z', 'h', 's', 't', 'snapshot'], conditional=False, description='JKU C++ simulator', gates=[GateConfig(name='TODO', parameters=[], qasm_def='TODO')], local=True, max_shots=100000, memory=True, n_qubits=30, open_pulse=False, simulator=True, url='https://github.com/Qiskit/qiskit-jku-provider')
```

**Comment by jaygambetta** [comment]
@chriseclectic and @diego-plan9 can you review this.

**Comment by yehuda-naveh** [comment]
@gadial you're in the best position to know if memory and conditionals are passed by default, and if not if that's the values we want

**Comment by gadial** [comment]
Memory should be set to **True** as JKU supports measurements to classical bits (if I understand correctly what "memory" stands for).

Conditional should be set to **False** since JKU does not support conditional branching statements (again, if I understand correctly what "conditional" stands for) when running on **qasm** inputs (there is a way to use conditionals in JKU if it used as a white box, but we do not do it in the wrapper).

I think we can close this issue.

**Comment by yehuda-naveh** [comment]
Thanks Gadi, sounds good
